"""Groups

Revision ID: a6b4edcab91e
Create Date: 2024-11-07 14:54:30.834081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b4edcab91e'
down_revision: Union[str, None] = '7d1725c0f14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuthToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GraphGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['Graph.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id', 'graph_id', 'group_id')
    )
    op.create_table('UserGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Boolean(), nullable=False),
    sa.Column('change_members', sa.Boolean(), nullable=False),
    sa.Column('add_graphs', sa.Boolean(), nullable=False),
    sa.Column('run_graphs', sa.Boolean(), nullable=False),
    sa.Column('change_graphs_permissions', sa.Boolean(), nullable=False),
    sa.Column('delete_graphs', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserGroup')
    op.drop_table('GraphGroup')
    op.drop_table('Group')
    op.drop_table('AuthToken')
    # ### end Alembic commands ###
